name: CI
on: [push, pull_request]

jobs:

  unit-test:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.5

      - name: Set HAXEPATH
        run: |
          echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV
      - name: Install Haxe dependencies
        run: |
          haxelib install lime --quiet
          haxelib install utest --quiet
          haxelib install hxp --quiet
      - name: Setup environment
        run: |
          haxelib dev openfl $GITHUB_WORKSPACE
      - name: Install "openfl" command alias
        run: |
          haxelib run openfl setup -alias -y
      - name: Run tests
        run: |
          haxelib run hxp --install-hxp-alias
          hxp test
  package-haxelib:
    runs-on: macos-10.15
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.5

      - name: Set HAXEPATH
        run: |
          echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV
      - name: Install Haxe dependencies
        run: |
          haxelib install hxp --quiet
      - name: Rebuild OpenFL run.n
        working-directory: scripts
        run: |
          haxe run.hxml
      - uses: actions/upload-artifact@v2
        with:
          name: openfl-haxelib
          path: |
            ./
            !tests/
            !haxe-*-*/
            !neko-*-*/
            !.git/
          if-no-files-found: error

  docs:
    runs-on: macos-10.15
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.5

      - name: Set HAXEPATH
        run: |
          echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV
      - name: Install Haxe dependencies
        run: |
          haxelib install lime 7.9.0 --quiet
          haxelib install openfl --quiet
          haxelib install flixel --quiet
          haxelib run lime setup --quiet
          haxelib run lime setup flixel --quiet
          haxelib install flixel-tools --quiet
          haxelib run flixel-tools setup --quiet
          haxelib install flixel-addons --quiet
          haxelib install flixel-ui --quiet
          haxelib install hscript --quiet
          haxelib install newgrounds --quiet
          haxelib install linc_luajit --quiet
          haxelib git faxe https://github.com/uhrobots/faxe --quiet
          haxelib install polymod --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet
          haxelib dev GameHaxe $GITHUB_WORKSPACE
      - name: Build docs
        working-directory: scripts
        run: |
          haxe docs.hxml
      - uses: actions/upload-artifact@v2
        with:
          name: openfl-docs
          path: docs
          if-no-files-found: error

  notify:
    runs-on: ubuntu-18.04
    needs: [package-haxelib, docs, unit-test]
    if: ${{ github.repository == 'openfl/openfl' && github.event_name != 'pull_request' }}
    steps:
      - name: Notify Discord
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          include-details: 'false'
