name: CI
on: [push, pull_request]

jobs:

  unit-test:
    runs-on: windows

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.5

      - name: Set HAXEPATH
        run: |
          haxelib install lime 7.9.0 --quiet
          haxelib install openfl --quiet
          haxelib install flixel --quiet
          haxelib run lime setup --quiet
          haxelib run lime setup flixel --quiet
          haxelib install flixel-tools --quiet
          haxelib run flixel-tools setup --quiet
          haxelib install flixel-addons --quiet
          haxelib install flixel-ui --quiet
          haxelib install hscript --quiet
          haxelib install newgrounds --quiet
          haxelib install linc_luajit --quiet
          haxelib git faxe https://github.com/uhrobots/faxe --quiet
          haxelib install polymod --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet
          haxelib dev GameHaxe $GITHUB_WORKSPACE
